export const SHOW_MODAL = "SHOW_MODAL";
export const HIDDEN_MODAL = "HINDDEN_MODAL";
export const CHANGE_MODAL_TITLE = "CHANGE_MODAL_TITLE";
export const CHANGE_MODAL_CONTENT = "CHANGE_MODAL_CONTENT";